name: 🐛 Bug Report
description: Report unexpected behavior, crashes, or defects.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before submitting
        * Ensure you’re using the latest version of application.
        * Check if the issue was already reported.

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser do you know to be affected?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Opera
        - Other? (Please let us know in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give us a summary of the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please tell us how to reproduce it (if applicable).
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version or commit hash of our software is affected?
      placeholder: e.g., v1.2.0 or commit hash
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: browser, logs, etc.
    validations:
      required: false