name: ❓ Question
description: Ask about usage, configuration, or troubleshooting
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps Taken
      description: What have you tried already?
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Step 3...

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, llama.ui version, hardware

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Logs, screenshots, or config files.